language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  # - "3.7"  #3.7 still gives Travis docker errors, python3.7 tested fine locally
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
env:
  - TOXENV=py27

install:
  # - pip install .
  # - pip install -r requirements_dev.txt

# command to run tests
script: nosetests

# whitelist
branches:
  only:
    - master
    - develop


deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: jpeyret
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: jpeyret/pynoorm
    condition: $TOXENV == py27